# CONDA ENVIRONMENT FILE
name: nf-train
channels:
  - conda-forge
  - bioconda
  - cyclus
  - defaults
dependencies:
  - cyclus::java-jdk
  - nextflow=21.10.0
  - salmon=1.5
  - fastqc=0.11.5
  - multiqc
  - kallisto=0.46.2
  - fastp=0.23.0
  - samtools
  - bioconda::nf-core=2.1
  